"""empty message

Revision ID: 068f1be8f993
Revises: 3eedcb405139
Create Date: 2024-05-01 22:13:27.746856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068f1be8f993'
down_revision: Union[str, None] = '3eedcb405139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chunk', ['id'], schema='region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunk', schema='region', type_='unique')
    # ### end Alembic commands ###
