"""add building queue

Revision ID: 1c40ab7aae64
Revises: ef7d4629479b
Create Date: 2024-05-05 15:37:50.910229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c40ab7aae64'
down_revision: Union[str, None] = 'ef7d4629479b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema queued;')
    op.create_table('building',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stronghold_id', sa.BigInteger(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=True),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.CheckConstraint('cell between 0 and 24', name='buildingqueue_stronghold_cell_0_to_24'),
    sa.ForeignKeyConstraint(['building_type_id'], ['stronghold.building_type.id'], ),
    sa.ForeignKeyConstraint(['stronghold_id'], ['stronghold.stronghold.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('stronghold_id', 'cell', name='uq_buildingqueue_stronghold_cell'),
    schema='queued'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building', schema='queued')
    op.execute('drop schema queued;')
    # ### end Alembic commands ###
