"""add user table

Revision ID: 34fbc134bf46
Revises: 
Create Date: 2024-04-23 23:14:07.020012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fbc134bf46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema common;')
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('created', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('cookie', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='common'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='common')
    op.execute('drop schema common;')
    # ### end Alembic commands ###
