"""add chunk

Revision ID: 3eedcb405139
Revises: 89e92d5ea6a3
Create Date: 2024-05-01 22:12:13.294962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eedcb405139'
down_revision: Union[str, None] = '89e92d5ea6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema region;')
    op.create_table('chunk',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('x_start', sa.BigInteger(), nullable=False),
    sa.Column('y_start', sa.BigInteger(), nullable=False),
    sa.Column('x_end', sa.BigInteger(), nullable=False),
    sa.Column('y_end', sa.BigInteger(), nullable=False),
    sa.Column('full', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='region'
    )
    op.add_column('stronghold', sa.Column('chunk_id', sa.BigInteger(), nullable=False), schema='stronghold')
    op.create_foreign_key(None, 'stronghold', 'chunk', ['chunk_id'], ['id'], source_schema='stronghold', referent_schema='region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stronghold', schema='stronghold', type_='foreignkey')
    op.drop_column('stronghold', 'chunk_id', schema='stronghold')
    op.drop_table('chunk', schema='region')
    op.execute('drop schema region;')
    # ### end Alembic commands ###
