"""add building price

Revision ID: 6fdb46995c89
Revises: 8d2f5b463f6e
Create Date: 2024-05-04 12:17:10.296812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdb46995c89'
down_revision: Union[str, None] = '8d2f5b463f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('materials', sa.Integer(), server_default='0', nullable=False),
    sa.Column('food', sa.Integer(), server_default='0', nullable=False),
    sa.Column('population', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time', sa.BigInteger(), server_default='1', nullable=False),
    sa.CheckConstraint('level > 0', name='building_price_level_gt_0'),
    sa.ForeignKeyConstraint(['building_type_id'], ['stronghold.building_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_type_id', 'level', name='uq_building_type_id_level'),
    schema='stronghold'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building_price', schema='stronghold')
    # ### end Alembic commands ###
