"""and building type and building tables

Revision ID: 7522a68444bf
Revises: 4bc7c3f72fad
Create Date: 2024-05-03 23:25:12.437030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7522a68444bf'
down_revision: Union[str, None] = '4bc7c3f72fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('icon_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('max_level', sa.Integer(), server_default='5', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon_name'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='stronghold'
    )
    op.create_table('building',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stronghold_id', sa.BigInteger(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=False),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('cell between 0 and 24', name='building_stronghold_cell_0_to_24'),
    sa.ForeignKeyConstraint(['building_type_id'], ['stronghold.building_type.id'], ),
    sa.ForeignKeyConstraint(['stronghold_id'], ['stronghold.stronghold.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('stronghold_id', 'cell', name='uq_building_stronghold_cell'),
    schema='stronghold'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building', schema='stronghold')
    op.drop_table('building_type', schema='stronghold')
    # ### end Alembic commands ###
