"""add structure

Revision ID: 752e8f1aa236
Revises: 85d93b0f960a
Create Date: 2024-05-04 16:09:47.500889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752e8f1aa236'
down_revision: Union[str, None] = '85d93b0f960a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema structure')
    op.create_table('structure_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('icon_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon_name'),
    sa.UniqueConstraint('name'),
    schema='structure'
    )
    op.create_table('structure',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('structure_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['region.chunk.id'], ),
    sa.ForeignKeyConstraint(['structure_type_id'], ['structure.structure_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['common.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='structure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structure', schema='structure')
    op.drop_table('structure_type', schema='structure')
    op.execute('drop schema structure')
    # ### end Alembic commands ###
