"""queue.building change uq

Revision ID: 80201da037f6
Revises: 2afacdd8fd60
Create Date: 2024-05-10 13:28:19.262731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80201da037f6'
down_revision: Union[str, None] = '2afacdd8fd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_buildingqueue_stronghold_cell', 'building', schema='queued', type_='unique')
    op.create_unique_constraint('uq_buildingqueue_stronghold_cell', 'building', ['stronghold_id', 'cell', 'done'], schema='queued')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_buildingqueue_stronghold_cell', 'building', schema='queued', type_='unique')
    op.create_unique_constraint('uq_buildingqueue_stronghold_cell', 'building', ['stronghold_id', 'cell'], schema='queued')
    # ### end Alembic commands ###
