"""add queued bool to queue.building

Revision ID: 8091f90d6cc4
Revises: f80b6b7f1c50
Create Date: 2024-05-05 18:14:24.450776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8091f90d6cc4'
down_revision: Union[str, None] = 'f80b6b7f1c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('queued', sa.Boolean(), server_default='false', nullable=False), schema='queued')
    op.alter_column('building', 'done',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False,
               schema='queued')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'done',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='queued')
    op.drop_column('building', 'queued', schema='queued')
    # ### end Alembic commands ###
