"""stronghold_building add nullable

Revision ID: 85d93b0f960a
Revises: 6fdb46995c89
Create Date: 2024-05-04 13:33:30.641784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d93b0f960a'
down_revision: Union[str, None] = '6fdb46995c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'building_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='stronghold')
    op.alter_column('building', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'),
               schema='stronghold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'),
               schema='stronghold')
    op.alter_column('building', 'building_type_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='stronghold')
    # ### end Alembic commands ###
