"""empty message

Revision ID: 89e92d5ea6a3
Revises: fe075b335a19
Create Date: 2024-05-01 20:46:44.378317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e92d5ea6a3'
down_revision: Union[str, None] = 'fe075b335a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stronghold', ['id'], schema='stronghold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stronghold', schema='stronghold', type_='unique')
    # ### end Alembic commands ###
