"""add xy to structure

Revision ID: c4107c0cf2d2
Revises: 752e8f1aa236
Create Date: 2024-05-04 16:19:04.140484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4107c0cf2d2'
down_revision: Union[str, None] = '752e8f1aa236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structure', sa.Column('x_coordinate', sa.BigInteger(), nullable=False), schema='structure')
    op.add_column('structure', sa.Column('y_coordinate', sa.BigInteger(), nullable=False), schema='structure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structure', 'y_coordinate', schema='structure')
    op.drop_column('structure', 'x_coordinate', schema='structure')
    # ### end Alembic commands ###
