"""add resource gain

Revision ID: ef7d4629479b
Revises: c4107c0cf2d2
Create Date: 2024-05-05 13:46:33.559936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7d4629479b'
down_revision: Union[str, None] = 'c4107c0cf2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_gain',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('gold', sa.BigInteger(), server_default='10', nullable=False),
    sa.Column('materials', sa.BigInteger(), server_default='50', nullable=False),
    sa.Column('food', sa.BigInteger(), server_default='50', nullable=False),
    sa.Column('population', sa.BigInteger(), server_default='50', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['common.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='common'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_gain', schema='common')
    # ### end Alembic commands ###
