"""add gold to building price

Revision ID: f80b6b7f1c50
Revises: 1c40ab7aae64
Create Date: 2024-05-05 16:58:15.083131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80b6b7f1c50'
down_revision: Union[str, None] = '1c40ab7aae64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'building', ['id'], schema='queued')
    op.add_column('building_price', sa.Column('gold', sa.Integer(), server_default='0', nullable=False), schema='stronghold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building_price', 'gold', schema='stronghold')
    op.drop_constraint(None, 'building', schema='queued', type_='unique')
    # ### end Alembic commands ###
