"""user.cookie null

Revision ID: fdbdd62bf1b1
Revises: 34fbc134bf46
Create Date: 2024-04-23 23:35:23.690290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbdd62bf1b1'
down_revision: Union[str, None] = '34fbc134bf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'cookie',
               existing_type=sa.VARCHAR(length=400),
               nullable=True,
               schema='common')
    op.create_unique_constraint(None, 'user', ['id'], schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='common', type_='unique')
    op.alter_column('user', 'cookie',
               existing_type=sa.VARCHAR(length=400),
               nullable=False,
               schema='common')
    # ### end Alembic commands ###
