"""add stronghold

Revision ID: fe075b335a19
Revises: fdbdd62bf1b1
Create Date: 2024-05-01 20:43:37.968835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe075b335a19'
down_revision: Union[str, None] = 'fdbdd62bf1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create schema stronghold;')
    op.create_table('stronghold',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('x_coordinate', sa.BigInteger(), nullable=False),
    sa.Column('y_coordinate', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['common.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='stronghold'
    )
    op.add_column('user', sa.Column('money', sa.BigInteger(), server_default='100', nullable=False), schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'money', schema='common')
    op.drop_table('stronghold', schema='stronghold')
    op.execute('drop schema stronghold;')
    # ### end Alembic commands ###
